dynamixels: ['shoulder_roll_joint', 'shoulder_pitch_joint', 'elbow_roll_joint', 'elbow_pitch_joint', 'elbow_yaw_joint', 'wrist_pitch_joint', 'wrist_roll_joint', 'gripper_finger1_joint']

cyton_gamma_300:

  cyton_joint_trajectory_action_controller:
    controller:
      package: dynamixel_controllers
      module: joint_trajectory_action_controller
      type: JointTrajectoryActionController
    joint_trajectory_action_node:
      min_velocity: 0.25
      constraints:
        goal_time: 1.0

  shoulder_roll_position_controller:
    controller:
      package: dynamixel_controllers
      module: joint_position_controller
      type: JointPositionController
    joint_name: shoulder_roll_joint
    joint_speed: 5.0
    motor:
      id: 0
      init: 2831
      min: 302
      max: 3770

  shoulder_pitch_position_controller:
    controller:
      package: dynamixel_controllers
      module: joint_position_controller
      type: JointPositionController
    joint_name: shoulder_pitch_joint
    joint_speed: 5.0
    motor:
      id: 1
      init: 2831
      min: 760
      max: 3335

  elbow_roll_position_controller:
    controller:
      package: dynamixel_controllers
      module: joint_position_controller
      type: JointPositionController
    joint_name: elbow_roll_joint
    joint_speed: 5.0
    motor:
      id: 2
      init: 2831
      min: 324
      max: 3735

  elbow_pitch_position_controller:
    controller:
      package: dynamixel_controllers
      module: joint_position_controller
      type: JointPositionController
    joint_name: elbow_pitch_joint
    joint_speed: 5.0
    motor:
      id: 3
      init: 2831
      min: 750
      max: 3347

  elbow_yaw_position_controller:
    controller:
      package: dynamixel_controllers
      module: joint_position_controller
      type: JointPositionController
    joint_name: elbow_yaw_joint
    joint_speed: 5.0
    motor:
      id: 4
      init: 2831
      min: 740
      max: 3331

  wrist_pitch_position_controller:
    controller:
      package: dynamixel_controllers
      module: joint_position_controller
      type: JointPositionController
    joint_name: wrist_pitch_joint
    joint_speed: 5.0
    motor:
      id: 5
      init: 2831
      min: 756
      max: 3347

  wrist_roll_position_controller:
    controller:
      package: dynamixel_controllers
      module: joint_position_controller
      type: JointPositionController
    joint_name: wrist_roll_joint
    joint_speed: 5.0
    motor:
      id: 6
      init: 2831
      min: 337
      max: 3753

  gripper_position_controller:
    controller:
      package: dynamixel_controllers
      module: joint_position_controller
      type: JointPositionController
    joint_name: gripper_finger1_joint
    joint_speed: 5.0
    motor:
      id: 9
      init: 1024
      min: 512
      max: 3450


